# Generated by Django 5.0.6 on 2024-06-28 00:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('rut', models.IntegerField()),
                ('direccion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('precio', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Repartidor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion_pedido', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos_direccion', to='app.cliente')),
                ('estado_pedido', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.estado')),
                ('nombre_pedido', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos_nombre', to='app.cliente')),
                ('repartidor_pedido', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.repartidor')),
            ],
        ),
    ]
