# Generated by Django 5.0.6 on 2024-06-28 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_pedido_producto_pedido'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='direccion_pedido',
        ),
    ]
